version: "3.9"

services:
  plug-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Chamo.Pzo
    - POSTGRES_DB=usersDB