"""initial migration

Revision ID: 379e1f753044
Revises: 82a0b82a3147
Create Date: 2024-01-30 09:14:41.803438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e1f753044'
down_revision = '82a0b82a3147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
