"""added more fields to users table

Revision ID: c39fedaa00af
Revises: 98a3a264c2af
Create Date: 2024-02-18 19:32:50.790274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39fedaa00af'
down_revision = '98a3a264c2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('secondary_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('secondary_email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
