"""created tokenblocklist for blacklisting ips

Revision ID: d74adf2924b7
Revises: b893ec99ffd3
Create Date: 2024-03-13 09:06:53.962130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74adf2924b7'
down_revision = 'b893ec99ffd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblocklist',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokenblocklist')
    # ### end Alembic commands ###
